name: Selenium Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest # Using linux machine

    steps:
      - uses: actions/checkout@v2 # Checkout the code
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1 # Setup JAVA
        with:
          java-version: 1.8
      - name: Install Google Chrome # Using shell script to install Google Chrome
        run: |
          chmod +x InstallChrome.sh
      - name: Build with Ant
        run: ant -noinput -buildfile build.xml

      - name: Compiling and running project
        run: ant all