name: CI on Windows

on:
  push:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight


jobs:
  build:
    runs-on: windows-latest # Using linux machine

    steps:
      - uses: actions/checkout@v2 # Checkout the code
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1 # Setup JAVA
        with:
          java-version: 1.8

      - name: Build with Ant
        run: ant -noinput -buildfile build.xml

      - name: Compiling project
        run: ant all

      - name: Running project
        run: cd build/jar
          && java -jar build.jar -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver/chromedriver.exe